// Code generated by go-cache-generator. DO NOT EDIT.

package main

import (
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	registerAnnotation("userServiceImpl", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "#0",
		TTL:       "300",
	})
	registerAnnotation("userServiceImpl", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#result.ID",
		TTL:       "300",
	})
	registerAnnotation("userServiceImpl", "DeleteUser", &proxy.CacheAnnotation{
		Type:      "cacheevict",
		CacheName: "users",
		Key:       "#id",
		TTL:       "",
	})
}

func registerAnnotation(typeName, methodName string, annotation *proxy.CacheAnnotation) {
	proxy.RegisterAnnotation(nil, typeName, methodName, annotation)
}
