// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T02:01:43+08:00
// Interface: UserServiceInterface
// Package: cached (generated cache wrappers)

package cached

import (
	"github.com/coderiser/go-cache/pkg/core"
	gocache "github.com/coderiser/go-cache/pkg/cache"
	"github.com/coderiser/go-cache/examples/cron-job/model"
	"context"
	"fmt"
	"time"
	"github.com/coderiser/go-cache/examples/cron-job/service"
)

// cachedUserService 带缓存的包装实现
// 实现 service.UserServiceInterface 接口
type cachedUserService struct {
	decorated service.UserServiceInterface
	manager   core.CacheManager
}


// NewUserService 创建带缓存的UserService 实例（使用全局 Manager）
func NewUserService() service.UserServiceInterface {
	return NewUserServiceWithManager(gocache.GetGlobalManager())
}

// NewUserServiceWithManager 创建带缓存的UserService 实例（使用指定 Manager）
func NewUserServiceWithManager(manager core.CacheManager) service.UserServiceInterface {
	raw := service.NewUserService(manager)
	return &cachedUserService{
		decorated: raw,
		manager:   manager,
	}
}


// GetUser 带缓存的实现（@cacheable）
func (c *cachedUserService) GetUser(id int64) (*model.User, error) {
	// 1. 获取缓存
	cache, err := c.manager.GetCache("users")
	if err != nil {
		return c.decorated.GetUser(id)
	}
	
	// 2. 生成缓存 Key
	key := fmt.Sprintf("users:%v", id)
	
	// 3. 查询缓存
	if val, found, _ := cache.Get(context.Background(), key); found {
		return val.(*model.User), nil
	}
	
	// 4. 执行原始方法
	result, err := c.decorated.GetUser(id)
	if err != nil {
		return nil, err
	}
	
	// 5. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// CreateUser 带缓存更新的实现（@cacheput）
func (c *cachedUserService) CreateUser(name string) (*model.User, error) {
	// 1. 执行原始方法
	result, err := c.decorated.CreateUser(name)
	if err != nil {
		return nil, err
	}
	
	// 2. 更新缓存
	cache, err := c.manager.GetCache("users")
	if err != nil {
		return result, nil
	}
	
	// 3. 生成缓存 Key
	key := fmt.Sprintf("users:%v", name)
	
	// 4. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// UpdateUser 带缓存更新的实现（@cacheput）
func (c *cachedUserService) UpdateUser(id int64, name string) (*model.User, error) {
	// 1. 执行原始方法
	result, err := c.decorated.UpdateUser(id, name)
	if err != nil {
		return nil, err
	}
	
	// 2. 更新缓存
	cache, err := c.manager.GetCache("users")
	if err != nil {
		return result, nil
	}
	
	// 3. 生成缓存 Key
	key := fmt.Sprintf("users:%v", id)
	
	// 4. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// DeleteUser 带缓存清除的实现（@cacheevict）
func (c *cachedUserService) DeleteUser(id int64) error {
	// 1. 执行原始方法
	result, err := c.decorated.DeleteUser(id)
	if err != nil {
		return result, err
	}
	
	// 2. 清除缓存
	cache, err := c.manager.GetCache("users")
	if err != nil {
		return result, nil
	}
	
	// 3. 生成缓存 Key
	key := fmt.Sprintf("users:%v", id)
	
	// 4. 删除缓存
	_ = cache.Delete(context.Background(), key)
	
	return result, nil
}

// 确保实现接口
var _ service.UserServiceInterface = (*cachedUserService)(nil)
