// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T18:41:00+08:00
// Interface: UserServiceInterface

package service

import (
	"github.com/coderiser/go-cache/pkg/proxy"
	"github.com/coderiser/go-cache/examples/gin-web/model"
	"fmt"
)

// decoratedUserService 自动生成的装饰器包装器
// 实现 UserServiceInterface 接口，通过代理调用方法
type decoratedUserService struct {
	decorated *proxy.DecoratedService[*userService]
}

// NewDecoratedUserService 创建装饰后的服务（自动生成）
func NewDecoratedUserService(decorated *proxy.DecoratedService[*userService]) *decoratedUserService {
	return &decoratedUserService{decorated: decorated}
}


// GetUser 自动生成的方法实现
func (d *decoratedUserService) GetUser(id int64) (*model.User, error) {
	results, err := d.decorated.Invoke("GetUser", id)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	user, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return user, nil
}

// CreateUser 自动生成的方法实现
func (d *decoratedUserService) CreateUser(user *model.User) (*model.User, error) {
	results, err := d.decorated.Invoke("CreateUser", user)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	user, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return user, nil
}

// UpdateUser 自动生成的方法实现
func (d *decoratedUserService) UpdateUser(id int64, user *model.User) (*model.User, error) {
	results, err := d.decorated.Invoke("UpdateUser", id, user)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	user, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return user, nil
}

// DeleteUser 自动生成的方法实现
func (d *decoratedUserService) DeleteUser(id int64) error {
	results, err := d.decorated.Invoke("DeleteUser", id)
	if err != nil {
		return err
	}
	if len(results) == 0 {
		return fmt.Errorf("no result")
	}
	if errResult, ok := results[0].(error); ok {
		return errResult
	}
	return nil
}

// 确保实现接口
var _ UserServiceInterface = (*decoratedUserService)(nil)
