package scan

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/coderiser/go-cache/pkg/logger"
)

// Generator 代码生成器
type Generator struct {
	config *Config
}

// NewGenerator 创建生成器
func NewGenerator(config *Config) *Generator {
	return &Generator{config: config}
}

// Generate 生成缓存包装器代码
func (g *Generator) Generate(result *Result) error {
	for _, pkg := range result.Packages {
		for filePath, fileInfo := range pkg.Files {
			matcher := NewMatcher()
			matches := matcher.MatchAllFiles(fileInfo)

			if len(matches) == 0 {
				continue
			}

			code, err := g.generateFile(pkg, fileInfo, matches)
			if err != nil {
				return fmt.Errorf("generate file %s: %w", filePath, err)
			}

			outputPath := g.outputPath(filePath)
			if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
				return err
			}

			formatted, err := format.Source(code)
			if err != nil {
				return fmt.Errorf("format %s: %w", outputPath, err)
			}

			if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
				return err
			}

			if g.config.Verbose {
				logger.Debug("  ✅ Generated: %s", filepath.Base(outputPath))
			}
		}
	}

	return nil
}

// outputPath 计算输出文件路径
func (g *Generator) outputPath(sourcePath string) string {
	dir := filepath.Dir(sourcePath)
	base := filepath.Base(sourcePath)
	name := strings.TrimSuffix(base, ".go")
	return filepath.Join(dir, name+"_cached.go")
}

// generateFile 生成单个文件
func (g *Generator) generateFile(pkg *PackageInfo, fileInfo *FileInfo, matches map[string]*MatchResult) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gocache. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))

	// 收集所有需要的导入
	imports := g.collectImports(fileInfo, matches)

	buf.WriteString("import (\n")
	for _, imp := range imports {
		buf.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}
	buf.WriteString(")\n\n")

	var ifaceNames []string
	for name := range matches {
		ifaceNames = append(ifaceNames, name)
	}
	sort.Strings(ifaceNames)

	for _, ifaceName := range ifaceNames {
		match := matches[ifaceName]
		g.generateWrapper(&buf, match)
	}

	return buf.Bytes(), nil
}

// collectImports 收集所有需要的导入包
func (g *Generator) collectImports(fileInfo *FileInfo, matches map[string]*MatchResult) []string {
	importSet := make(map[string]bool)

	// 基础导入
	importSet["context"] = true
	importSet["time"] = true
	importSet["github.com/coderiser/go-cache/pkg/cache"] = true
	importSet["github.com/coderiser/go-cache/pkg/core"] = true
	importSet["github.com/coderiser/go-cache/pkg/spel"] = true

	// 从方法签名中收集类型导入
	for _, match := range matches {
		for _, method := range match.Interface.Methods {
			// 收集参数类型中的包
			for _, param := range method.Params {
				g.extractTypeImports(param.Type, fileInfo.Imports, importSet)
			}
			// 收集返回值类型中的包
			for _, ret := range method.Returns {
				g.extractTypeImports(ret.Type, fileInfo.Imports, importSet)
			}
		}
	}

	// 转换为排序后的切片
	var imports []string
	for imp := range importSet {
		imports = append(imports, imp)
	}
	sort.Strings(imports)

	return imports
}

// extractTypeImports 从类型字符串中提取包导入
// 例如：*model.User -> github.com/coderiser/go-cache/examples/gin-web/model
func (g *Generator) extractTypeImports(typeStr string, fileImports map[string]string, importSet map[string]bool) {
	// 移除指针、切片等前缀
	typeStr = strings.TrimPrefix(typeStr, "*")
	typeStr = strings.TrimPrefix(typeStr, "[]")
	typeStr = strings.TrimPrefix(typeStr, "map[")

	// 查找包路径：查找当前包路径 + 类型名
	// 例如：*model.User 需要从 fileImports 中找到 model 对应的完整路径
	parts := strings.Split(typeStr, ".")
	if len(parts) == 2 {
		alias := parts[0]
		// 从 fileImports 中查找 alias 对应的完整路径
		for impPath, impAlias := range fileImports {
			if impAlias == alias || (impAlias == "" && filepath.Base(impPath) == alias) {
				importSet[impPath] = true
				return
			}
		}
	}
}

// generateWrapper 生成单个服务的缓存包装器
func (g *Generator) generateWrapper(buf *bytes.Buffer, match *MatchResult) {
	iface := match.Interface
	svc := match.Service

	structName := "cached" + strings.Title(svc.TypeName)
	globalVarName := g.globalVarName(iface.Name)

	buf.WriteString(fmt.Sprintf("// %s 缓存包装器\n", structName))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	buf.WriteString(fmt.Sprintf("\traw       *%s\n", svc.TypeName))
	buf.WriteString("\tmanager   core.CacheManager\n")
	buf.WriteString("\tevaluator *spel.SpELEvaluator\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("// %s 全局实例\n", globalVarName))
	buf.WriteString(fmt.Sprintf("var %s %s\n\n", globalVarName, iface.Name))

	g.generateConstructor(buf, iface, svc, structName, globalVarName)
	g.generateInitFunc(buf, iface, svc, structName, globalVarName)

	for _, method := range iface.Methods {
		methodInfo, exists := svc.Methods[method.Name]
		if !exists {
			continue
		}
		g.generateMethod(buf, iface, svc, structName, method, methodInfo)
	}

	buf.WriteString(fmt.Sprintf("var _ %s = (*%s)(nil)\n\n", iface.Name, structName))
}

// globalVarName 计算全局变量名
// UserServiceInterface -> UserService
// OrderService -> Order
func (g *Generator) globalVarName(ifaceName string) string {
	return strings.TrimSuffix(ifaceName, "Interface")
}

// generateConstructor 生成构造函数
func (g *Generator) generateConstructor(buf *bytes.Buffer, iface *InterfaceInfo, svc *ServiceInfo, structName, globalVarName string) {
	funcName := "NewCached" + strings.Title(svc.TypeName)

	buf.WriteString(fmt.Sprintf("// %s 创建带缓存的服务实例\n", funcName))
	buf.WriteString(fmt.Sprintf("func %s(", funcName))

	if svc.Constructor != nil && len(svc.Constructor.Params) > 0 {
		params := make([]string, len(svc.Constructor.Params))
		for i, p := range svc.Constructor.Params {
			params[i] = fmt.Sprintf("%s %s", p.Name, p.Type)
		}
		buf.WriteString(strings.Join(params, ", "))
	}

	buf.WriteString(fmt.Sprintf(") %s {\n", iface.Name))

	if svc.Constructor != nil && len(svc.Constructor.Params) > 0 {
		args := make([]string, len(svc.Constructor.Params))
		for i, p := range svc.Constructor.Params {
			args[i] = p.Name
		}
		buf.WriteString(fmt.Sprintf("\traw := %s(%s)\n", svc.Constructor.Name, strings.Join(args, ", ")))
	} else {
		buf.WriteString(fmt.Sprintf("\traw := &%s{}\n", svc.TypeName))
	}

	buf.WriteString("\treturn &" + structName + "{\n")
	buf.WriteString("\t\traw:       raw,\n")
	buf.WriteString("\t\tmanager:   cache.GetGlobalManager(),\n")
	buf.WriteString("\t\tevaluator: spel.NewSpELEvaluator(),\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")
}

// generateInitFunc 生成初始化函数
func (g *Generator) generateInitFunc(buf *bytes.Buffer, iface *InterfaceInfo, svc *ServiceInfo, structName, globalVarName string) {
	funcName := "Init" + strings.Title(svc.TypeName)

	buf.WriteString(fmt.Sprintf("// %s 初始化全局实例\n", funcName))
	buf.WriteString(fmt.Sprintf("func %s(", funcName))

	if svc.Constructor != nil && len(svc.Constructor.Params) > 0 {
		params := make([]string, len(svc.Constructor.Params))
		for i, p := range svc.Constructor.Params {
			params[i] = fmt.Sprintf("%s %s", p.Name, p.Type)
		}
		buf.WriteString(strings.Join(params, ", "))
	}

	buf.WriteString(") {\n")

	if svc.Constructor != nil && len(svc.Constructor.Params) > 0 {
		args := make([]string, len(svc.Constructor.Params))
		for i, p := range svc.Constructor.Params {
			args[i] = p.Name
		}
		buf.WriteString(fmt.Sprintf("\t%s = NewCached%s(%s)\n", globalVarName, strings.Title(svc.TypeName), strings.Join(args, ", ")))
	} else {
		buf.WriteString(fmt.Sprintf("\t%s = NewCached%s()\n", globalVarName, strings.Title(svc.TypeName)))
	}

	buf.WriteString("}\n\n")
}

// generateMethod 生成方法实现
func (g *Generator) generateMethod(buf *bytes.Buffer, iface *InterfaceInfo, svc *ServiceInfo, structName string, methodSpec *MethodSpec, methodInfo *MethodInfo) {
	buf.WriteString(fmt.Sprintf("func (c *%s) %s(", structName, methodSpec.Name))

	if len(methodSpec.Params) > 0 {
		params := make([]string, len(methodSpec.Params))
		for i, p := range methodSpec.Params {
			params[i] = fmt.Sprintf("%s %s", p.Name, p.Type)
		}
		buf.WriteString(strings.Join(params, ", "))
	}

	buf.WriteString(") ")

	if len(methodSpec.Returns) > 0 {
		if len(methodSpec.Returns) > 1 || methodSpec.Returns[0].Name != "" {
			buf.WriteString("(")
			returns := make([]string, len(methodSpec.Returns))
			for i, r := range methodSpec.Returns {
				returns[i] = r.Type
			}
			buf.WriteString(strings.Join(returns, ", "))
			buf.WriteString(")")
		} else {
			buf.WriteString(methodSpec.Returns[0].Type)
		}
	}

	buf.WriteString(" {\n")

	switch methodInfo.Operation {
	case "cacheable":
		g.generateCacheableMethod(buf, methodSpec, methodInfo)
	case "cacheput":
		g.generateCachePutMethod(buf, methodSpec, methodInfo)
	case "cacheevict":
		g.generateCacheEvictMethod(buf, methodSpec, methodInfo)
	default:
		buf.WriteString("\t// Unknown operation\n")
	}

	buf.WriteString("}\n\n")
}

// generateCacheableMethod 生成 cacheable 方法
func (g *Generator) generateCacheableMethod(buf *bytes.Buffer, methodSpec *MethodSpec, methodInfo *MethodInfo) {
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString(fmt.Sprintf("\tcache, _ := c.manager.GetCache(\"%s\")\n\n", methodInfo.Cache))

	buf.WriteString("\t// 构建缓存 Key\n")
	buf.WriteString("\tevalCtx := spel.NewEvaluationContext()\n")

	for i, param := range methodSpec.Params {
		buf.WriteString(fmt.Sprintf("\tevalCtx.SetArg(\"%s\", %s)\n", param.Name, param.Name))
		buf.WriteString(fmt.Sprintf("\tevalCtx.SetArgByIndex(%d, %s)\n", i, param.Name))
	}

	buf.WriteString(fmt.Sprintf("\tkey, _ := c.evaluator.EvaluateToString(\"%s\", evalCtx)\n\n", methodInfo.Key))

	buf.WriteString("\t// 查缓存\n")
	buf.WriteString("\tif val, found, _ := cache.Get(ctx, key); found {\n")

	if len(methodSpec.Returns) > 0 {
		returnType := methodSpec.Returns[0].Type
		if strings.HasPrefix(returnType, "*") || strings.HasPrefix(returnType, "[]") || strings.HasPrefix(returnType, "map[") {
			buf.WriteString(fmt.Sprintf("\t\treturn val.(%s), nil\n", returnType))
		} else {
			buf.WriteString(fmt.Sprintf("\t\treturn val.(%s), nil\n", returnType))
		}
	} else {
		buf.WriteString("\t\treturn\n")
	}

	buf.WriteString("\t}\n\n")

	buf.WriteString("\t// 调用原始方法\n")
	rawCall := g.generateRawCall(methodSpec)
	buf.WriteString(fmt.Sprintf("\t%s\n\n", rawCall))

	// 错误处理：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 && strings.Contains(methodSpec.Returns[len(methodSpec.Returns)-1].Type, "error") {
		buf.WriteString("\tif err != nil {\n")
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\t\treturn nil, err\n")
		} else {
			buf.WriteString("\t\treturn err\n")
		}
		buf.WriteString("\t}\n\n")
	}

	buf.WriteString("\t// 写缓存\n")
	ttl := g.parseTTL(methodInfo.TTL)
	buf.WriteString(fmt.Sprintf("\tcache.Set(ctx, key, result, %s)\n\n", ttl))

	// 返回值：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 {
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\treturn result, nil\n")
		} else {
			buf.WriteString("\treturn nil\n")
		}
	} else {
		buf.WriteString("\treturn\n")
	}
}

// generateCachePutMethod 生成 cacheput 方法
func (g *Generator) generateCachePutMethod(buf *bytes.Buffer, methodSpec *MethodSpec, methodInfo *MethodInfo) {
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString(fmt.Sprintf("\tcache, _ := c.manager.GetCache(\"%s\")\n\n", methodInfo.Cache))

	buf.WriteString("\t// 调用原始方法\n")
	rawCall := g.generateRawCall(methodSpec)
	buf.WriteString(fmt.Sprintf("\t%s\n\n", rawCall))

	// 错误处理：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 && strings.Contains(methodSpec.Returns[len(methodSpec.Returns)-1].Type, "error") {
		buf.WriteString("\tif err != nil {\n")
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\t\treturn nil, err\n")
		} else {
			buf.WriteString("\t\treturn err\n")
		}
		buf.WriteString("\t}\n\n")
	}

	buf.WriteString("\t// 构建缓存 Key\n")
	buf.WriteString("\tevalCtx := spel.NewEvaluationContext()\n")

	if len(methodSpec.Returns) > 0 {
		buf.WriteString("\tevalCtx.SetResult(result)\n")
	}

	buf.WriteString(fmt.Sprintf("\tkey, _ := c.evaluator.EvaluateToString(\"%s\", evalCtx)\n\n", methodInfo.Key))

	buf.WriteString("\t// 写缓存\n")
	ttl := g.parseTTL(methodInfo.TTL)
	buf.WriteString(fmt.Sprintf("\tcache.Set(ctx, key, result, %s)\n\n", ttl))

	// 返回值：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 {
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\treturn result, nil\n")
		} else {
			buf.WriteString("\treturn nil\n")
		}
	} else {
		buf.WriteString("\treturn\n")
	}
}

// generateCacheEvictMethod 生成 cacheevict 方法
func (g *Generator) generateCacheEvictMethod(buf *bytes.Buffer, methodSpec *MethodSpec, methodInfo *MethodInfo) {
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString(fmt.Sprintf("\tcache, _ := c.manager.GetCache(\"%s\")\n\n", methodInfo.Cache))

	if methodInfo.Before {
		buf.WriteString("\t// 先删除缓存\n")
		g.generateEvictKey(buf, methodSpec, methodInfo)
		buf.WriteString("\tcache.Delete(ctx, key)\n\n")
	}

	buf.WriteString("\t// 调用原始方法\n")
	rawCall := g.generateRawCall(methodSpec)
	buf.WriteString(fmt.Sprintf("\t%s\n\n", rawCall))

	// 错误处理：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 && strings.Contains(methodSpec.Returns[len(methodSpec.Returns)-1].Type, "error") {
		buf.WriteString("\tif err != nil {\n")
		// 如果有多个返回值（如 *T, error），返回 nil, err
		// 如果只有一个 error 返回值，返回 err
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\t\treturn nil, err\n")
		} else {
			buf.WriteString("\t\treturn err\n")
		}
		buf.WriteString("\t}\n\n")
	}

	if !methodInfo.Before {
		buf.WriteString("\t// 后删除缓存\n")
		g.generateEvictKey(buf, methodSpec, methodInfo)
		buf.WriteString("\tcache.Delete(ctx, key)\n\n")
	}

	// 返回值：根据返回值数量决定返回格式
	if len(methodSpec.Returns) > 0 {
		if len(methodSpec.Returns) > 1 {
			buf.WriteString("\treturn result, nil\n")
		} else {
			// 只有 error 返回值的情况已经在上面处理了，这里不需要再返回
			buf.WriteString("\treturn nil\n")
		}
	} else {
		buf.WriteString("\treturn\n")
	}
}

// generateEvictKey 生成删除缓存的 key 构建代码
func (g *Generator) generateEvictKey(buf *bytes.Buffer, methodSpec *MethodSpec, methodInfo *MethodInfo) {
	buf.WriteString("\tevalCtx := spel.NewEvaluationContext()\n")

	for i, param := range methodSpec.Params {
		buf.WriteString(fmt.Sprintf("\tevalCtx.SetArg(\"%s\", %s)\n", param.Name, param.Name))
		buf.WriteString(fmt.Sprintf("\tevalCtx.SetArgByIndex(%d, %s)\n", i, param.Name))
	}

	buf.WriteString(fmt.Sprintf("\tkey, _ := c.evaluator.EvaluateToString(\"%s\", evalCtx)\n", methodInfo.Key))
}

// generateRawCall 生成调用原始方法的代码
func (g *Generator) generateRawCall(methodSpec *MethodSpec) string {
	var args []string
	for _, p := range methodSpec.Params {
		args = append(args, p.Name)
	}

	call := fmt.Sprintf("result, err := c.raw.%s(%s)", methodSpec.Name, strings.Join(args, ", "))

	if len(methodSpec.Returns) == 0 {
		call = fmt.Sprintf("c.raw.%s(%s)", methodSpec.Name, strings.Join(args, ", "))
	} else if len(methodSpec.Returns) == 1 {
		if strings.Contains(methodSpec.Returns[0].Type, "error") {
			call = fmt.Sprintf("err := c.raw.%s(%s)", methodSpec.Name, strings.Join(args, ", "))
		}
	}

	return call
}

// parseTTL 解析 TTL 字符串，生成可读的 Go 代码
func (g *Generator) parseTTL(ttl string) string {
	if ttl == "" {
		return "30 * time.Minute"
	}

	d, err := time.ParseDuration(ttl)
	if err != nil {
		return "30 * time.Minute"
	}

	// 优化：使用合适的单位，提高代码可读性
	if d >= time.Hour && d%time.Hour == 0 {
		return fmt.Sprintf("%d * time.Hour", d/time.Hour)
	}
	if d >= time.Minute && d%time.Minute == 0 {
		return fmt.Sprintf("%d * time.Minute", d/time.Minute)
	}
	if d >= time.Second && d%time.Second == 0 {
		return fmt.Sprintf("%d * time.Second", d/time.Second)
	}
	return fmt.Sprintf("%d * time.Nanosecond", d.Nanoseconds())
}
