// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T01:25:18+08:00
// Total annotations: 3

package cached

import (
	"github.com/coderiser/go-cache/pkg/proxy"
	gocache "github.com/coderiser/go-cache/pkg/cache"
)

func init() {
	gocache.RegisterGlobalAnnotation("productService", "GetProduct", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "products",
		Key:       "#id",
		TTL:       "1h",
	})
	gocache.RegisterGlobalAnnotation("productService", "GetHotProducts", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "hot_products",
		Key:       "list",
		TTL:       "5m",
	})
	gocache.RegisterGlobalAnnotation("productService", "UpdatePrice", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "products",
		Key:       "#id",
		TTL:       "1h",
	})
}
