// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T18:42:22+08:00
// Total annotations: 3

package registry

import (
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	proxy.RegisterAnnotation(nil, "productService", "GetProduct", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "products",
		Key:       "id",
		TTL:       "1h",
	})
	proxy.RegisterAnnotation(nil, "productService", "GetHotProducts", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "hot_products",
		Key:       "list",
		TTL:       "5m",
	})
	proxy.RegisterAnnotation(nil, "productService", "UpdatePrice", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "products",
		Key:       "id",
		TTL:       "1h",
	})
}
