// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T01:25:18+08:00
// Interface: ProductServiceInterface
// Package: cached (generated cache wrappers)

package cached

import (
	"fmt"
	"time"
	"github.com/coderiser/go-cache/pkg/core"
	gocache "github.com/coderiser/go-cache/pkg/cache"
	"github.com/coderiser/go-cache/examples/cron-job/model"
	"context"
	"github.com/coderiser/go-cache/examples/cron-job/service"
)

// cachedProductService 带缓存的包装实现
// 实现 service.ProductServiceInterface 接口
type cachedProductService struct {
	decorated service.ProductServiceInterface
	manager   core.CacheManager
}


// NewProductService 创建带缓存的ProductService 实例（使用全局 Manager）
func NewProductService() service.ProductServiceInterface {
	return NewProductServiceWithManager(gocache.GetGlobalManager())
}

// NewProductServiceWithManager 创建带缓存的ProductService 实例（使用指定 Manager）
func NewProductServiceWithManager(manager core.CacheManager) service.ProductServiceInterface {
	raw := service.NewProductService(manager)
	return &cachedProductService{
		decorated: raw,
		manager:   manager,
	}
}


// GetProduct 带缓存的实现（@cacheable）
func (c *cachedProductService) GetProduct(id int64) (*model.Product, error) {
	// 1. 获取缓存
	cache, err := c.manager.GetCache("products")
	if err != nil {
		return c.decorated.GetProduct(id)
	}
	
	// 2. 生成缓存 Key
	key := fmt.Sprintf("products:%v", id)
	
	// 3. 查询缓存
	if val, found, _ := cache.Get(context.Background(), key); found {
		return val.(*model.Product), nil
	}
	
	// 4. 执行原始方法
	result, err := c.decorated.GetProduct(id)
	if err != nil {
		return nil, err
	}
	
	// 5. 写入缓存
	ttl, _ := time.ParseDuration("1h")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// GetHotProducts 带缓存的实现（@cacheable）
func (c *cachedProductService) GetHotProducts() ([]*model.Product, error) {
	// 1. 获取缓存
	cache, err := c.manager.GetCache("hot_products")
	if err != nil {
		return c.decorated.GetHotProducts()
	}
	
	// 2. 生成缓存 Key
	key := fmt.Sprintf("hot_products:%v", "default")
	
	// 3. 查询缓存
	if val, found, _ := cache.Get(context.Background(), key); found {
		return val.([]*model.Product), nil
	}
	
	// 4. 执行原始方法
	result, err := c.decorated.GetHotProducts()
	if err != nil {
		return nil, err
	}
	
	// 5. 写入缓存
	ttl, _ := time.ParseDuration("5m")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// UpdatePrice 带缓存更新的实现（@cacheput）
func (c *cachedProductService) UpdatePrice(id int64, price float64) (*model.Product, error) {
	// 1. 执行原始方法
	result, err := c.decorated.UpdatePrice(id, price)
	if err != nil {
		return nil, err
	}
	
	// 2. 更新缓存
	cache, err := c.manager.GetCache("products")
	if err != nil {
		return result, nil
	}
	
	// 3. 生成缓存 Key
	key := fmt.Sprintf("products:%v", id)
	
	// 4. 写入缓存
	ttl, _ := time.ParseDuration("1h")
	_ = cache.Set(context.Background(), key, result, ttl)
	
	return result, nil
}

// GetAllProducts 透传方法（无缓存）
func (c *cachedProductService) GetAllProducts() []*model.Product {
	return c.decorated.GetAllProducts()
}

// GetProductByID 透传方法（无缓存）
func (c *cachedProductService) GetProductByID(id int64) *model.Product {
	return c.decorated.GetProductByID(id)
}

// UpdateStock 透传方法（无缓存）
func (c *cachedProductService) UpdateStock(id int64, stock int) error {
	return c.decorated.UpdateStock(id, stock)
}

// 确保实现接口
var _ service.ProductServiceInterface = (*cachedProductService)(nil)
