// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T01:59:04+08:00
// Total annotations: 4

package cached

import (
	"github.com/coderiser/go-cache/pkg/proxy"
	gocache "github.com/coderiser/go-cache/pkg/cache"
)

func init() {
	gocache.RegisterGlobalAnnotation("userService", "UpdateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#id",
		TTL:       "30m",
	})
	gocache.RegisterGlobalAnnotation("userService", "DeleteUser", &proxy.CacheAnnotation{
		Type:      "cacheevict",
		CacheName: "users",
		Key:       "#id",
	})
	gocache.RegisterGlobalAnnotation("userService", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "#id",
		TTL:       "30m",
	})
	gocache.RegisterGlobalAnnotation("userService", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#result.ID",
		TTL:       "30m",
	})
}
