package generator

// wrapperTemplate is the template for generating wrapper code
const wrapperTemplate = `// Code generated by generator; DO NOT EDIT.
// Source: @cacheable annotated methods

package {{.Package}}

import (
	"generator/proxy"
)
{{range .Services}}
{{$serviceName := .Name}}
{{$implType := .ImplType}}

// {{.Name}} is the decorated wrapper for {{.ImplType}}
type {{.Name}} struct {
	decorated *proxy.DecoratedService[*{{.ImplType}}]
}

// New{{.Name}} creates a new {{.Name}} instance
func New{{.Name}}(decorated *proxy.DecoratedService[*{{.ImplType}}]) *{{.Name}} {
	return &{{.Name}}{decorated: decorated}
}
{{range .Methods}}
{{$method := .}}
{{$results := .Results}}

// {{.Name}} is the decorated version of {{$implType}}.{{.Name}}
{{if .Annotation}}// @cacheable(cache="{{.Annotation.CacheName}}", key="{{.Annotation.Key}}", ttl="{{.Annotation.TTL}}"){{end}}
func (d *{{$serviceName}}) {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) ({{range $i, $r := .Results}}{{if $i}}, {{end}}{{$r.Type}}{{end}}) {
	results, err := d.decorated.Invoke("{{.Name}}", {{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}}{{end}})
	if err != nil {
{{- $hasError := false }}{{- range $r := $results }}{{- if eq $r.Type "error" }}{{ $hasError = true }}{{- end }}{{- end }}
{{- if $hasError }}
{{- range $i, $r := $results }}{{- if eq $r.Type "error" }}
{{- range $j, $r2 := $results }}{{- if ne $j $i }}
		var zero{{$j}} {{$r2.Type}}
{{- end }}{{- end }}
		return {{ range $j, $r2 := $results }}{{- if $j }}, {{- end }}{{- if eq $j $i }}err{{- else }}zero{{$j}}{{- end }}{{- end }}
{{- end }}{{- end }}
{{- else }}
{{- range $i, $r := $results }}
		var zero{{$i}} {{$r.Type}}
{{- end }}
		return {{ range $i, $r := $results }}{{- if $i }}, {{- end }}zero{{$i}}{{- end }}, err
{{- end }}
	}
{{- range $i, $r := $results}}
	result{{$i}}, _ := results[{{$i}}].({{$r.Type}})
{{- end}}
	return {{range $i, $r := $results}}{{if $i}}, {{end}}result{{$i}}{{end}}
}
{{end}}
{{end}}
`

// registryTemplate is the template for generating registry code
const registryTemplate = `// Code generated by generator; DO NOT EDIT.
// Source: @cacheable annotated methods

package {{.Package}}

import (
	"generator/proxy"
)

// Registry holds all decorated service instances
type Registry struct {
{{range .Services}}	{{.Name}} *{{.Name}}
{{end}}
}

// NewRegistry creates a new Registry with all decorated services
func NewRegistry() *Registry {
	return &Registry{
{{range .Services}}		{{.Name}}: New{{.Name}}(proxy.NewDecoratedService[*{{.ImplType}}](nil)),
{{end}}
	}
}

// RegisterService registers a service instance with the registry
func (r *Registry) RegisterService(impl interface{}) {
	switch v := impl.(type) {
{{range .Services}}	case *{{.ImplType}}:
		r.{{.Name}} = New{{.Name}}(proxy.NewDecoratedService(v))
{{end}}
	}
}

// GetService returns a service by name
func (r *Registry) GetService(name string) interface{} {
	switch name {
{{range .Services}}	case "{{.ImplType}}":
		return r.{{.Name}}
{{end}}
	default:
		return nil
	}
}
`
