// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T02:37:39+08:00
// Total annotations: 4

package cached

import (
	gocache "github.com/coderiser/go-cache/pkg/cache"
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	gocache.RegisterGlobalAnnotation("orderService", "GetOrder", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "orders",
		Key:       "#id",
		TTL:       "30m",
	})
	gocache.RegisterGlobalAnnotation("orderService", "CreateOrder", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "orders",
		Key:       "#result.ID",
		TTL:       "30m",
	})
	gocache.RegisterGlobalAnnotation("userService", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#result.ID",
		TTL:       "30m",
	})
	gocache.RegisterGlobalAnnotation("userService", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "#id",
		TTL:       "30m",
	})
}
