// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T02:37:39+08:00
// Interface: OrderServiceInterface
// Package: cached (generated cache wrappers)

package cached

import (
	"context"
	"fmt"
	"github.com/coderiser/go-cache/examples/grpc-demo/model"
	"github.com/coderiser/go-cache/examples/grpc-demo/service"
	gocache "github.com/coderiser/go-cache/pkg/cache"
	"github.com/coderiser/go-cache/pkg/core"
	"time"
)

// cachedOrderService 带缓存的包装实现
// 实现 service.OrderServiceInterface 接口
type cachedOrderService struct {
	decorated service.OrderServiceInterface
	manager   core.CacheManager
}

// NewOrderService 创建带缓存的OrderService 实例（使用全局 Manager）
func NewOrderService() service.OrderServiceInterface {
	return NewOrderServiceWithManager(gocache.GetGlobalManager())
}

// NewOrderServiceWithManager 创建带缓存的OrderService 实例（使用指定 Manager）
func NewOrderServiceWithManager(manager core.CacheManager) service.OrderServiceInterface {
	raw := service.NewOrderService(manager)
	return &cachedOrderService{
		decorated: raw,
		manager:   manager,
	}
}

// GetOrder 带缓存的实现（@cacheable）
func (c *cachedOrderService) GetOrder(id int64) (*model.Order, error) {
	// 1. 获取缓存
	cache, err := c.manager.GetCache("orders")
	if err != nil {
		return c.decorated.GetOrder(id)
	}

	// 2. 生成缓存 Key
	key := fmt.Sprintf("%s:%v", id)

	// 3. 查询缓存
	if val, found, _ := cache.Get(context.Background(), key); found {
		return val.(*model.Order), nil
	}

	// 4. 执行原始方法
	result, err := c.decorated.GetOrder(id)
	if err != nil {
		return nil, err
	}

	// 5. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)

	return result, nil
}

// CreateOrder 带缓存更新的实现（@cacheput）
func (c *cachedOrderService) CreateOrder(userID int64, total float64) (*model.Order, error) {
	// 1. 执行原始方法
	result, err := c.decorated.CreateOrder(userID, total)
	if err != nil {
		return nil, err
	}

	// 2. 更新缓存
	cache, err := c.manager.GetCache("orders")
	if err != nil {
		return result, nil
	}

	// 3. 生成缓存 Key
	key := fmt.Sprintf("%s:%v", result.ID)

	// 4. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)

	return result, nil
}

// 确保实现接口
var _ service.OrderServiceInterface = (*cachedOrderService)(nil)
