// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T18:42:22+08:00
// Interface: ProductServiceInterface

package service

import (
	"fmt"
	"github.com/coderiser/go-cache/pkg/proxy"
	"github.com/coderiser/go-cache/examples/cron-job/model"
)

// decoratedProductService 自动生成的装饰器包装器
// 实现 ProductServiceInterface 接口，通过代理调用方法
type decoratedProductService struct {
	decorated *proxy.DecoratedService[*productService]
}

// NewDecoratedProductService 创建装饰后的服务（自动生成）
func NewDecoratedProductService(decorated *proxy.DecoratedService[*productService]) *decoratedProductService {
	return &decoratedProductService{decorated: decorated}
}


// GetProduct 自动生成的方法实现
func (d *decoratedProductService) GetProduct(id int64) (*model.Product, error) {
	results, err := d.decorated.Invoke("GetProduct", id)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	product, ok := results[0].(*model.Product)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return product, nil
}

// GetHotProducts 自动生成的方法实现
func (d *decoratedProductService) GetHotProducts() ([]*model.Product, error) {
	results, err := d.decorated.Invoke("GetHotProducts")
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	product, ok := results[0].([]*model.Product)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return product, nil
}

// UpdatePrice 自动生成的方法实现
func (d *decoratedProductService) UpdatePrice(id int64, price float64) (*model.Product, error) {
	results, err := d.decorated.Invoke("UpdatePrice", id, price)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result")
	}
	product, ok := results[0].(*model.Product)
	if !ok {
		return nil, fmt.Errorf("wrong type")
	}
	return product, nil
}

// GetAllProducts 自动生成的方法实现
func (d *decoratedProductService) GetAllProducts() []*model.Product {
	results, err := d.decorated.Invoke("GetAllProducts")
	if err != nil {
		return nil
	}
	if len(results) == 0 {
		return nil
	}
	product, ok := results[0].([]*model.Product)
	if !ok {
		return nil
	}
	return product
}

// GetProductByID 自动生成的方法实现
func (d *decoratedProductService) GetProductByID(id int64) *model.Product {
	results, err := d.decorated.Invoke("GetProductByID", id)
	if err != nil {
		return nil
	}
	if len(results) == 0 {
		return nil
	}
	product, ok := results[0].(*model.Product)
	if !ok {
		return nil
	}
	return product
}

// UpdateStock 自动生成的方法实现
func (d *decoratedProductService) UpdateStock(id int64, stock int) error {
	results, err := d.decorated.Invoke("UpdateStock", id, stock)
	if err != nil {
		return err
	}
	if len(results) == 0 {
		return fmt.Errorf("no result")
	}
	if errResult, ok := results[0].(error); ok {
		return errResult
	}
	return nil
}

// 确保实现接口
var _ ProductServiceInterface = (*decoratedProductService)(nil)
