// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T18:21:33+08:00
// Total annotations: 4

package registry

import (
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	proxy.RegisterAnnotation(nil, "userService", "DeleteUser", &proxy.CacheAnnotation{
		Type:      "cacheevict",
		CacheName: "users",
		Key:       "id",
	})
	proxy.RegisterAnnotation(nil, "userService", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "id",
		TTL:       "30m",
	})
	proxy.RegisterAnnotation(nil, "userService", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "user.ID",
		TTL:       "30m",
	})
	proxy.RegisterAnnotation(nil, "userService", "UpdateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "id",
		TTL:       "30m",
	})
}
