// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T12:56:00+08:00
// Total annotations: 4

package registry

import (
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	// UserService.GetUser - @cacheable(cache="users", key="#id", ttl="30m")
	proxy.RegisterAnnotation(nil, "UserService", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "#id",
		TTL:       "30m",
	})
	
	// UserService.CreateUser - @cacheput(cache="users", key="#result.ID", ttl="30m")
	proxy.RegisterAnnotation(nil, "UserService", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#result.ID",
		TTL:       "30m",
	})
	
	// UserService.UpdateUser - @cacheput(cache="users", key="#user.ID", ttl="30m")
	proxy.RegisterAnnotation(nil, "UserService", "UpdateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "#user.ID",
		TTL:       "30m",
	})
	
	// UserService.DeleteUser - @cacheevict(cache="users", key="#id", before=false)
	proxy.RegisterAnnotation(nil, "UserService", "DeleteUser", &proxy.CacheAnnotation{
		Type:      "cacheevict",
		CacheName: "users",
		Key:       "#id",
		Before:    false,
	})
}
