// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T15:51:09+08:00
// Total annotations: 4

package service

import (
	"log"
	"github.com/coderiser/go-cache/pkg/proxy"
)

func init() {
	log.Println("[DEBUG] anno_generated.go init() executing...")
	proxy.RegisterAnnotation(nil, "userService", "GetUser", &proxy.CacheAnnotation{
		Type:      "cacheable",
		CacheName: "users",
		Key:       "id",
		TTL:       "1800",
	})
	proxy.RegisterAnnotation(nil, "userService", "CreateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "user.ID",
		TTL:       "1800",
	})
	proxy.RegisterAnnotation(nil, "userService", "UpdateUser", &proxy.CacheAnnotation{
		Type:      "cacheput",
		CacheName: "users",
		Key:       "id",
		TTL:       "1800",
	})
	proxy.RegisterAnnotation(nil, "userService", "DeleteUser", &proxy.CacheAnnotation{
		Type:      "cacheevict",
		CacheName: "users",
		Key:       "id",
	})
	log.Println("[DEBUG] anno_generated.go init() completed. Registered 4 annotations for userService")
}
