// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-13T18:21:33+08:00
// Interface: UserServiceInterface

package service

import (
	"fmt"
	"github.com/coderiser/go-cache/pkg/proxy"
	"github.com/coderiser/go-cache/examples/gin-web/model"
)

// DecoratedUserService 自动生成的装饰服务包装器
// 实现 UserServiceInterface 接口，通过代理调用方法
type DecoratedUserService struct {
	decorated *proxy.DecoratedService[*userService]
}

// NewDecoratedUserService 创建装饰后的服务实例
func NewDecoratedUserService(decorated *proxy.DecoratedService[*userService]) *DecoratedUserService {
	return &DecoratedUserService{decorated: decorated}
}


// GetUser GetUser（通过代理调用）
func (d *DecoratedUserService) GetUser(id int64) (*model.User, error) {
	results, err := d.decorated.Invoke("GetUser", id)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result returned")
	}
	result, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("unexpected result type: %T", results[0])
	}
	return result, nil
}

// CreateUser CreateUser（通过代理调用）
func (d *DecoratedUserService) CreateUser(user *model.User) (*model.User, error) {
	results, err := d.decorated.Invoke("CreateUser", user)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result returned")
	}
	result, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("unexpected result type: %T", results[0])
	}
	return result, nil
}

// UpdateUser UpdateUser（通过代理调用）
func (d *DecoratedUserService) UpdateUser(id int64, user *model.User) (*model.User, error) {
	results, err := d.decorated.Invoke("UpdateUser", id, user)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no result returned")
	}
	result, ok := results[0].(*model.User)
	if !ok {
		return nil, fmt.Errorf("unexpected result type: %T", results[0])
	}
	return result, nil
}

// DeleteUser DeleteUser（通过代理调用）
func (d *DecoratedUserService) DeleteUser(id int64) error {
	results, err := d.decorated.Invoke("DeleteUser", id)
	if err != nil {
		return err
	}
	if len(results) == 0 {
		return fmt.Errorf("no result returned")
	}
	if errResult, ok := results[0].(error); ok {
		return errResult
	}
	return nil
}

// 确保 DecoratedUserService 实现了 UserServiceInterface 接口
var _ UserServiceInterface = (*DecoratedUserService)(nil)
