// Code generated by go-cache-gen. DO NOT EDIT.
// Generated at: 2026-03-14T03:08:56+08:00
// Interface: OrderServiceInterface

package service

import (
	"context"
	"fmt"
	"time"

	"github.com/coderiser/go-cache/examples/gin-web/model"
	gocache "github.com/coderiser/go-cache/pkg/cache"
	"github.com/coderiser/go-cache/pkg/core"
)

// cachedOrderService 带缓存的包装实现
// 实现 OrderServiceInterface 接口
type cachedOrderService struct {
	decorated OrderServiceInterface
	manager   core.CacheManager
}

// NewOrderService 创建带缓存的OrderService 实例（使用全局 Manager）
func NewOrderService() OrderServiceInterface {
	return NewOrderServiceWithManager(gocache.GetGlobalManager())
}

// NewOrderServiceWithManager 创建带缓存的OrderService 实例（使用指定 Manager）
func NewOrderServiceWithManager(manager core.CacheManager) OrderServiceInterface {
	raw := NewOrderServiceRaw()
	return &cachedOrderService{
		decorated: raw,
		manager:   manager,
	}
}

// GetOrder 带缓存的实现（@cacheable）
func (c *cachedOrderService) GetOrder(id int64) (*model.Order, error) {
	// 1. 获取缓存
	cache, err := c.manager.GetCache("orders")
	if err != nil {
		return c.decorated.GetOrder(id)
	}

	// 2. 生成缓存 Key
	key := fmt.Sprintf("orders:%v", id)

	// 3. 查询缓存
	if val, found, _ := cache.Get(context.Background(), key); found {
		return val.(*model.Order), nil
	}

	// 4. 执行原始方法
	result, err := c.decorated.GetOrder(id)
	if err != nil {
		return nil, err
	}

	// 5. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)

	return result, nil
}

// CreateOrder 带缓存更新的实现（@cacheput）
func (c *cachedOrderService) CreateOrder(userID int64, total float64) (*model.Order, error) {
	// 1. 执行原始方法
	result, err := c.decorated.CreateOrder(userID, total)
	if err != nil {
		return nil, err
	}

	// 2. 更新缓存
	cache, err := c.manager.GetCache("orders")
	if err != nil {
		return result, nil
	}

	// 3. 生成缓存 Key
	key := fmt.Sprintf("orders:%v", result.ID)

	// 4. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)

	return result, nil
}

// UpdateOrderStatus 带缓存更新的实现（@cacheput）
func (c *cachedOrderService) UpdateOrderStatus(id int64, status string) (*model.Order, error) {
	// 1. 执行原始方法
	result, err := c.decorated.UpdateOrderStatus(id, status)
	if err != nil {
		return nil, err
	}

	// 2. 更新缓存
	cache, err := c.manager.GetCache("orders")
	if err != nil {
		return result, nil
	}

	// 3. 生成缓存 Key
	key := fmt.Sprintf("orders:%v", id)

	// 4. 写入缓存
	ttl, _ := time.ParseDuration("30m")
	_ = cache.Set(context.Background(), key, result, ttl)

	return result, nil
}

// 确保实现接口
var _ OrderServiceInterface = (*cachedOrderService)(nil)
